/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cocinapaty;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

/**
 *
 * @author slimline
 */
public class postres extends javax.swing.JFrame {

    Estacion est;
    String cafame;
    Productos prod;
    JTextArea ticket;
    double total=0;
    int numBebida;
    double precioUnit;
    double precioInt;
    String linea1,lineaTicket;
    /**
     * Creates new form postres
     */
    public postres(Estacion est) 
    {
        initComponents();
        this.est=est;
        prod = new Productos();
        prod.generaProd();
        ticket = new JTextArea();
        
        ManejadorPostre manejaPostres = new ManejadorPostre();
        jButton2.addActionListener(manejaPostres);
        jButton3.addActionListener(manejaPostres);
        jButton4.addActionListener(manejaPostres);
        jButton5.addActionListener(manejaPostres);
        jButton1.addActionListener(manejaPostres);
        
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    public void addProducto(Estacion est,String linea)
        {
            est.addProductoEst(linea);
        }
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSpinner9 = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jSpinner10 = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jSpinner11 = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSpinner12 = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jSpinner13 = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 514));

        jScrollPane2.setName("jScrollPane2");

        jPanel2.setName("jPanel2");

        jLayeredPane1.setName("jLayeredPane1");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logochico.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setName("jLabel1");
        jLabel1.setBounds(10, 10, 150, 70);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/postres/selvanegra.png"))); // NOI18N
        jButton1.setText("Selva Negra");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setName("jButton1");
        jButton1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.setBounds(20, 710, 127, 130);
        jLayeredPane1.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/postres/brownie.png"))); // NOI18N
        jButton2.setText("Brownie");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setName("jButton2");
        jButton2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.setBounds(20, 120, 127, 130);
        jLayeredPane1.add(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/postres/pastel3leches.png"))); // NOI18N
        jButton3.setText("Pastel 3 Leches");
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setName("jButton3");
        jButton3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.setBounds(20, 260, 127, 130);
        jLayeredPane1.add(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/postres/heladodefresa.png"))); // NOI18N
        jButton4.setText("Helado Fresa");
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setName("jButton4");
        jButton4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.setBounds(20, 405, 127, 130);
        jLayeredPane1.add(jButton4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/postres/paydezarzamora.png"))); // NOI18N
        jButton5.setText("Pay Zarzamora");
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setName("jButton5");
        jButton5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jButton5.setBounds(20, 550, 127, 130);
        jLayeredPane1.add(jButton5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setText("Precio ");
        jLabel2.setName("jLabel2");
        jLabel2.setBounds(150, 125, 40, 14);
        jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel19.setText("$ 38.00");
        jLabel19.setName("jLabel19");
        jLabel19.setBounds(200, 125, 60, 14);
        jLayeredPane1.add(jLabel19, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setText("Cantidad");
        jLabel3.setName("jLabel3");
        jLabel3.setBounds(150, 145, 50, 14);
        jLayeredPane1.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jSpinner9.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        jSpinner9.setName("jSpinner9");
        jSpinner9.setBounds(200, 145, 40, 20);
        jLayeredPane1.add(jSpinner9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setText("Precio ");
        jLabel4.setName("jLabel4");
        jLabel4.setBounds(150, 270, 40, 14);
        jLayeredPane1.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel5.setText("Cantidad");
        jLabel5.setName("jLabel5");
        jLabel5.setBounds(150, 290, 50, 14);
        jLayeredPane1.add(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel20.setText("$ 37.00");
        jLabel20.setName("jLabel20");
        jLabel20.setBounds(200, 270, 60, 14);
        jLayeredPane1.add(jLabel20, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jSpinner10.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        jSpinner10.setName("jSpinner10");
        jSpinner10.setBounds(200, 285, 40, 20);
        jLayeredPane1.add(jSpinner10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel6.setText("Precio ");
        jLabel6.setName("jLabel6");
        jLabel6.setBounds(150, 420, 40, 14);
        jLayeredPane1.add(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel7.setText("Cantidad");
        jLabel7.setName("jLabel7");
        jLabel7.setBounds(150, 440, 50, 14);
        jLayeredPane1.add(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel21.setText("$ 32.00");
        jLabel21.setName("jLabel21");
        jLabel21.setBounds(200, 420, 60, 14);
        jLayeredPane1.add(jLabel21, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jSpinner11.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        jSpinner11.setName("jSpinner11");
        jSpinner11.setBounds(200, 440, 40, 20);
        jLayeredPane1.add(jSpinner11, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel8.setText("Precio ");
        jLabel8.setName("jLabel8");
        jLabel8.setBounds(150, 560, 40, 14);
        jLayeredPane1.add(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel22.setText("$ 40.00");
        jLabel22.setName("jLabel22");
        jLabel22.setBounds(200, 560, 60, 14);
        jLayeredPane1.add(jLabel22, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel9.setText("Cantidad");
        jLabel9.setName("jLabel9");
        jLabel9.setBounds(150, 580, 50, 14);
        jLayeredPane1.add(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jSpinner12.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        jSpinner12.setName("jSpinner12");
        jSpinner12.setBounds(200, 580, 40, 20);
        jLayeredPane1.add(jSpinner12, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel10.setText("Precio ");
        jLabel10.setName("jLabel10");
        jLabel10.setBounds(155, 715, 40, 14);
        jLayeredPane1.add(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel23.setText("$ 36.00");
        jLabel23.setName("jLabel23");
        jLabel23.setBounds(205, 715, 60, 14);
        jLayeredPane1.add(jLabel23, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jSpinner13.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        jSpinner13.setName("jSpinner13");
        jSpinner13.setBounds(205, 735, 40, 20);
        jLayeredPane1.add(jSpinner13, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel11.setText("Cantidad");
        jLabel11.setName("jLabel11");
        jLabel11.setBounds(155, 735, 50, 14);
        jLayeredPane1.add(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondopostre.png"))); // NOI18N
        jLabel12.setName("jLabel12");
        jLabel12.setBounds(0, 0, 380, 850);
        jLayeredPane1.add(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 381, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jScrollPane2.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner10;
    private javax.swing.JSpinner jSpinner11;
    private javax.swing.JSpinner jSpinner12;
    private javax.swing.JSpinner jSpinner13;
    private javax.swing.JSpinner jSpinner9;
    // End of variables declaration//GEN-END:variables

private class ManejadorPostre implements ActionListener
    {
        @Override
        public void actionPerformed(ActionEvent botonProducto)
        {
            numBebida = 0;
            precioUnit = 0;
            precioInt = 0;
            linea1 = "";
            lineaTicket = "";
            if(botonProducto.getSource()==jButton2)
            {
                cafame = jSpinner9.getValue().toString(); 
                linea1 = cafame +prod.getValorComp(18, 0)+"\n";
                addProducto(est,linea1);
                numBebida = Integer.parseInt(jSpinner9.getValue().toString());
                precioUnit = Double.parseDouble(prod.getValorComp(18, 1));
                precioInt = numBebida*precioUnit;
                total = total + precioInt;
                System.out.println(precioInt);
                lineaTicket = cafame+"  "+prod.getValorComp(18,0)+"  "+prod.getValorComp(18, 1)+"  "+precioInt+"\n";
                ticket.append(lineaTicket);
            }
            if(botonProducto.getSource()==jButton3)
            {
                cafame = jSpinner10.getValue().toString();
                linea1 = cafame + " "+ prod.getValorComp(19, 0)+"\n";
                addProducto(est,linea1);
                numBebida = Integer.parseInt(jSpinner10.getValue().toString());
                precioUnit = Double.parseDouble(prod.getValorComp(19, 1));
                precioInt = numBebida*precioUnit;
                total = total + precioInt;
                System.out.println(precioInt);
                lineaTicket = cafame+"  "+prod.getValorComp(19, 0)+"  "+prod.getValorComp(19, 1)+"  "+precioInt+"\n";
                ticket.append(lineaTicket);
            }
            if(botonProducto.getSource()==jButton4)
            {
                cafame = jSpinner11.getValue().toString();
                linea1 = cafame + " "+ prod.getValorComp(20, 0)+"\n";
                addProducto(est,linea1);
                numBebida = Integer.parseInt(jSpinner11.getValue().toString());
                precioUnit = Double.parseDouble(prod.getValorComp(20, 1));
                precioInt = numBebida*precioUnit;
                total = total + precioInt;
                System.out.println(precioInt);
                lineaTicket = cafame+"  "+prod.getValorComp(20, 0)+"  "+prod.getValorComp(20, 1)+"  "+precioInt+"\n";
                ticket.append(lineaTicket);
            }
            if(botonProducto.getSource()==jButton5)
            {
                cafame = jSpinner12.getValue().toString();
                linea1 = cafame + " "+ prod.getValorComp(21, 0)+"\n";
                addProducto(est,linea1);
                numBebida = Integer.parseInt(jSpinner12.getValue().toString());
                precioUnit = Double.parseDouble(prod.getValorComp(21, 1));
                precioInt = numBebida*precioUnit;
                total = total + precioInt;
                System.out.println(precioInt);
                lineaTicket = cafame+"  "+prod.getValorComp(21, 0)+"  "+prod.getValorComp(21, 1)+"  "+precioInt+"\n";
                ticket.append(lineaTicket);
            }
            if(botonProducto.getSource()==jButton1)
            {
                cafame = jSpinner13.getValue().toString();
                linea1 = cafame + " "+ prod.getValorComp(22, 0)+"\n";
                addProducto(est,linea1);
                numBebida = Integer.parseInt(jSpinner13.getValue().toString());
                precioUnit = Double.parseDouble(prod.getValorComp(22, 1));
                precioInt = numBebida*precioUnit;
                total = total + precioInt;
                System.out.println(precioInt);
                lineaTicket = cafame+"  "+prod.getValorComp(22, 0)+"  "+prod.getValorComp(22, 1)+"  "+precioInt+"\n";
                ticket.append(lineaTicket);
            }
            
            JOptionPane.showMessageDialog(null,ticket,"Ticket", JOptionPane.INFORMATION_MESSAGE);
        }
    }
}
